In [2]:
from collections import defaultdict
import torch
state = defaultdict(dict)

In [3]:
gg = torch.tensor([1., 2., 3.])

In [7]:
tmp = torch.zeros_like(gg)
tmp

tensor([0., 0., 0.])

In [6]:
tmp.copy_(gg.mul(5).add(torch.tensor([1, 1, 1])))

tensor([ 6., 11., 16.])

In [8]:
gg

tensor([1., 2., 3.])

In [17]:
gg.mul_(4)

tensor([ 4.,  8., 12.])

In [20]:
param_state['ii'] = 2

In [22]:
data = param_state['ii']

In [25]:
param_state['ii'] = torch.tensor([1, 2])

In [26]:
param_state

{'gg': 2, 'ii': tensor([1, 2])}

In [27]:
data = param_state['ii']

In [28]:
data = torch.tensor([3, 4])

In [29]:
param_state

{'gg': 2, 'ii': tensor([1, 2])}

In [3]:
a = torch.ones(3, 3)

In [1]:
import random

In [9]:
class A:
    def __init__(self):
        pass

    def gg(self):
        print(self.a)

class B(A):
    def __init__(self):
        self.a = "GGG"


In [10]:
bb = B()

In [11]:
bb.gg()

GGG
